name: Create Release

on:
  workflow_call:
    inputs:
      release_name_prefix:
        description: "Optional prefix for the release title"
        type: string
        default: ""
      release_tag:
        description: "Release Tag"
        required: true
        type: string
    secrets:
      PAT_RELEASE_TOKEN:
        required: true

permissions:
  contents: write

concurrency:
  group: release-${{ github.repository }}
  cancel-in-progress: false

jobs:
  create_release:
    name: Create New Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog since previous tag
        id: changelog
        shell: bash
        run: |
          set -euo pipefail
          tag='${{ inputs.release_tag }}'

          # Resolve the commit the new tag points to (works for annotated or lightweight)
          tag_commit="$(git rev-list -n 1 "$tag")"

          # Previous tag reachable before this tag's commit; `${tag}^` starts the search at the parent of the tagged commit
          prev="$(git describe --tags --abbrev=0 "${tag}^" 2>/dev/null || true)"

          if [ -n "$prev" ]; then
            range="${prev}..${tag_commit}"
          else
            # No previous tag: only include the tagged commit (or the range since repo start if you prefer)
            range="${tag_commit}^..${tag_commit}"
          fi

          # Build notes; drop merge commits (remove --no-merges if you want them)
          notes="$(git log $range --pretty=format:'- %s' --no-merges || true)"

          echo "notes<<EOF" >>"$GITHUB_OUTPUT"
          echo "${notes:-No notable changes.}" >>"$GITHUB_OUTPUT"
          echo "EOF" >>"$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.PAT_RELEASE_TOKEN }}
          tag_name: ${{ inputs.release_tag }}
          name: ${{ inputs.release_name_prefix }}${{ inputs.release_tag }}
          body: ${{ steps.changelog.outputs.notes }}
          draft: false
          prerelease: false
